from django.urls import path
from .views import *

urlpatterns = [
    path('', index),
    path('login-user', login_user),
    path('accounts/login/', redirect_login),
    path('check-email',check_email),
    path('change_email', change_email),
    path('homework-upload', homework_upload),
    path('homework-create', homework_create),
    path('homework-upload-teach-answer', homework_upload_teach_answer),
    path('message-file-upload/<str:time>/<str:name>/<int:number>/<str:href>', message_file_upload),
    path('update-profile-picture', update_profile_picture),
    path('delete-profile-picture', delete_profile_picture),
    path('send_request_v', send_request_view),
    path('send_request_fl', send_request_first_lesson),
    path('send_request_vt', send_request_view_teach),
    path('change-info', change_info),
    path('change-info-reg', change_info_reg),
    path('change-password', change_password),
    path('change-additional-info', change_additional_info),
    path('save-blog/<int:number>',save_blog),
    path('ask_question', ask_question),
    path('add_word_tape', add_word_tape),
    path('price', price),
    path('confidentiality', confidentiality),
    path('oferta', oferta),
    path('ajax_load_lessons/<int:number>', ajax_load_lessons),
    path('ajax_load_homework/<int:number>', ajax_load_homework),
    path('ajax_delete_word/<int:number>', ajax_delete_word),
    path('ajax_delete_homework/<int:number>', ajax_delete_homework),
    path('ajax_load_course_lessons/<int:number>', ajax_load_course_lessons),
    path('ajax_pay_lessons', ajax_pay_lessons),
    path('ajax_load_interactives/<int:number>', ajax_load_interactives),
    path('ajax_load_interactive_list/<int:number>', ajax_load_interactive_list),
    path('ajax_load_lessons_videos/<int:number>', ajax_load_lessons_videos),
    path('ajax_load_video/<int:number>', ajax_load_video),
    path('ajax_load_lessons_audios/<int:number>', ajax_load_lessons_audios),
    path('ajax_load_homework_audios/<int:number>', ajax_load_homework_audios),
    path('ajax_load_homework_videos/<int:number>', ajax_load_homework_videos),
    path('ajax_load_homework_files/<int:number>', ajax_load_homework_files),
    path('ajax_load_homework_files_pup_ans/<int:number>', ajax_load_homework_files_pup_ans),
    path('ajax_load_homework_files_teach_ans/<int:number>', ajax_load_homework_files_teach_ans),
    path('ajax_load_messages/<str:name>', ajax_load_messages),
    path('ajax_load_course_homeworks/<int:number>',ajax_load_course_homeworks),
    path('accounts/password_reset/done/', password_reset_done),
    path('ajax_load_url_file_messages/<int:userid>/<str:roomname>/<str:time>/<str:message>', ajax_load_url_file_messages),
    path('accounts/reset/done/', password_reset_complete),
    path('dashboard/account', dashboard_account),
    path('dashboard/lk', dashboard_lk),
    path('dashboard/platform', dashboard_platform),
    path('dashboard/schedule', dashboard_schedule),
    path('dashboard/homework', dashboard_homework),
    path('dashboard/tape', dashboard_tape),
    path('dashboard/courses', dashboard_courses),
    path('dashboard/blog/<int:number>', dashboard_blog),
    path('logout', loggout),
    path('courses_adult', courses_adult),
    path('courses_kid', courses_kid),
    path('blogs', blogs),
    path('thanks', thanks),
    path('blog/<int:number>', blog),
    path('video/<int:number>', video),
    path('video-constructor/<int:number>', video_constructor),
    path('video-listening/<int:number>', video_listening),
    path('check_aswer/<int:number>', check_answer),
    path('send_call_request', call_request)
]
