version: '3.1'

services:
  web:
    build: ./
    command: ./docker-entrypoint.sh
    volumes:
      - ./:/web
    ports:
      - "443:443"
      - "80:80"
  redis:
    image: "redis:alpine"
    ports:
      - "127.0.0.1:6378:6378"


